const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const shared=read('functions/shared/ops-analytics-contract.js');
const central=read('functions/api/admin/central-dashboard.js');
const intel=read('functions/api/admin/ops-intelligence.js');
const okazu=read('functions/api/admin/okazu-analytics.js');
const dash=read('assets/ops-dashboard.js');
const intelUi=read('assets/ops-intelligence.js');
const okazuUi=read('assets/ops-okazu.js');
const html=read('ops-dashboard.html');
assert(shared.includes('CENTRAL_CLICK_SQL="(\'affiliate_click\',\'affiliate_click_unified\')"'));
assert(shared.includes("VEHICLE_CLICK_EVENTS=['affiliate_click','affiliate_click_unified','affiliate_slot_click','car_valuation_click','bike_buyback_click','rakuten_click']"));
assert(central.includes("const carClause=`AND c.site_key<>'car-bike'`;"));
assert(intel.includes("const carClause=`AND c.site_key<>'car-bike'`;"));
assert(!central.includes('central-fallback'));
assert(central.includes('vehicle-unavailable'));
assert(central.includes('CENTRAL_CLICK_SQL')&&intel.includes('CENTRAL_CLICK_SQL')&&okazu.includes('CENTRAL_CLICK_SQL'));
assert(okazu.includes('const filteredPeriod=')&&okazu.includes('SUSPICIOUS_BROWSER_SQL'));
assert(dash.includes("new CustomEvent('ops:period-ready'"));
assert(dash.includes('const requestDays=days;const seq=++loadSeq'));
assert(intelUi.includes("window.addEventListener('ops:period-ready'"));
assert(okazuUi.includes("window.addEventListener('ops:period-ready'"));
assert(html.includes('/assets/ops-dashboard.js?v=20261003-1'));
assert(html.includes('/assets/ops-intelligence.js?v=20261003-1'));
console.log('Analytics consistency QA passed.');
