// Production QA for norimono-cost.com revenue, SEO, affiliate experiments and performance.
const {test,expect}=require('@playwright/test');
const base='https://norimono-cost.com';
test.setTimeout(90000);
async function gotoStable(page,route,waitMs=1200){const errors=[];page.removeAllListeners('pageerror');page.on('pageerror',e=>errors.push(String(e?.message||e)));const response=await page.goto(`${base}${route}`,{waitUntil:'load',timeout:45000});expect(response?.status(),`${route}: HTTP status`).toBeLessThan(400);await page.waitForTimeout(waitMs);expect(errors.filter(x=>!/ResizeObserver loop limit exceeded/i.test(x)),`${route}: uncaught JS errors`).toEqual([])}
function expectValidMoney(text,label){const value=String(text||'').trim();expect(value,`${label}: empty`).not.toBe('');expect(value,`${label}: invalid`).not.toMatch(/NaN|Infinity/i);expect(value,`${label}: digit`).toMatch(/\d/)}
async function chooseCar(page,brand,model){await page.waitForFunction(()=>document.querySelector('#cvBrand')?.options.length>1,{timeout:20000});await page.locator('#cvBrand').selectOption(brand);await page.waitForFunction(expected=>[...document.querySelectorAll('#cvModel option')].some(o=>o.value===expected),model,{timeout:15000});await page.locator('#cvModel').selectOption(model);const years=await page.locator('#cvYear option').evaluateAll(options=>options.map(o=>o.value).filter(Boolean));if(years.length)await page.locator('#cvYear').selectOption(years.includes('2021')?'2021':years[0]);await page.locator('#cvMileage').fill('40000');await page.locator('#carValueForm button[type="submit"]').click();await page.waitForTimeout(250)}

test('deployment marker and canonical sitemap are live',async({request})=>{const marker=await request.get(`${base}/deploy-marker.txt`);expect(marker.status()).toBeLessThan(400);expect(await marker.text()).toContain('v115-github-production-qa');const robots=await request.get(`${base}/robots.txt`);expect(robots.status()).toBeLessThan(400);const robotText=await robots.text();const sitemapLines=robotText.split(/\r?\n/).filter(x=>/^Sitemap:/i.test(x.trim()));expect(sitemapLines).toEqual(['Sitemap: https://norimono-cost.com/sitemap-index.xml']);const sitemap=await request.get(`${base}/sitemap-index.xml`);expect(sitemap.status()).toBeLessThan(400);const xml=await sitemap.text();for(const name of ['sitemap.xml','vehicle-search-priority-v74-sitemap.xml','bike-rankings-sitemap.xml','goods-sitemap.xml','car-compare-guides-sitemap.xml','bike-compare-guides-sitemap.xml'])expect(xml,`sitemap index: ${name}`).toContain(name)});

test('representative vehicle SEO and revenue paths are live',async({page})=>{const cases=[['/cars/honda-n-box','/car-value'],['/cars/toyota-hiace-wagon','/car-value'],['/cars/toyota-harrier','/car-value'],['/cars/toyota-sienta','/car-value'],['/cars/suzuki-jimny','/car-value'],['/bikes/honda-rebel-250','/bike-value'],['/bikes/honda-pcx','/bike-value'],['/bikes/kawasaki-ninja-250','/bike-value'],['/bikes/honda-gb350','/bike-value']];for(const [route,valueHref] of cases){await gotoStable(page,route,500);await expect(page.locator('[data-vehicle-revenue-paths="1"]'),`${route}: revenue paths`).toBeVisible();expect(await page.locator(`[data-vehicle-revenue-paths="1"] a[href^="${valueHref}"]`).count(),`${route}: value path`).toBeGreaterThan(0);await expect(page.locator('[data-popular-seo-v115="1"]'),`${route}: popular SEO`).toBeVisible()}});

test('expanded popular vehicle SEO pages are server-rendered and live',async({request})=>{const routes=['/cars/suzuki-spacia','/cars/daihatsu-tanto','/cars/honda-freed','/cars/toyota-aqua','/cars/honda-fit','/bikes/yamaha-nmax','/bikes/yamaha-yzf-r25','/bikes/honda-super-cub-110','/bikes/honda-hunter-cub-ct125','/bikes/kawasaki-z900rs'];for(const route of routes){const r=await request.get(base+route);expect(r.status(),`${route}: status`).toBeLessThan(400);const html=await r.text();expect(html,`${route}: popular SEO marker`).toContain('data-popular-seo-v115="1"');expect(html,`${route}: revenue paths`).toContain('data-vehicle-revenue-paths="1"')}});

test('vehicle detail revenue paths carry exact vehicle context',async({page})=>{const cases=[['/cars/honda-n-box','ホンダ','N-BOX','/car-value','/car-goods'],['/bikes/honda-rebel-250','ホンダ','Rebel 250','/bike-value','/bike-goods']];for(const [route,brand,model,valuePath,goodsPath] of cases){await gotoStable(page,route,700);const links=await page.locator('[data-vehicle-revenue-paths="1"] a').evaluateAll(as=>as.map(a=>a.href));const value=links.find(h=>new URL(h).pathname===valuePath);const goods=links.find(h=>new URL(h).pathname===goodsPath);expect(value,`${route}: contextual value URL`).toBeTruthy();expect(goods,`${route}: contextual goods URL`).toBeTruthy();const vu=new URL(value),gu=new URL(goods);expect(vu.searchParams.get('brand')).toBe(brand);expect(vu.searchParams.get('model')).toBe(model);expect(gu.searchParams.get('q')).toContain(brand);expect(gu.searchParams.get('q')).toContain(model)}});

test('QUICK COST is valid on representative car and bike detail pages',async({page})=>{for(const route of ['/cars/honda-n-box','/bikes/honda-rebel-250']){await gotoStable(page,route,700);const quick=page.locator('#quick-cost');await expect(quick,`${route}: QUICK COST`).toBeVisible();for(const selector of ['[data-quick-annual]','[data-quick-monthly]','[data-quick-fuel]']){const text=await quick.locator(selector).textContent();expect(String(text||''),`${route}: ${selector}`).toContain('円');expectValidMoney(text,`${route}: ${selector}`)}}});

test('car value diagnosis works for ordinary, van and truck',async({page})=>{for(const [brand,model] of [['ホンダ','N-BOX'],['トヨタ','ハイエースバン'],['ホンダ','アクティトラック']]){await gotoStable(page,'/car-value',900);await chooseCar(page,brand,model);expect(await page.locator('#cvVehicleName').textContent()).toContain(model);expectValidMoney(await page.locator('#cvCurrentValue').textContent(),`${model}: current`);expectValidMoney(await page.locator('#cvTradeValue').textContent(),`${model}: trade`)}});

test('Rebel 250 bike value is live',async({page})=>{await gotoStable(page,'/bike-value',900);await page.waitForFunction(()=>document.querySelector('#bvBrand')?.options.length>1,{timeout:20000});await page.locator('#bvBrand').selectOption('ホンダ');await page.waitForFunction(()=>[...document.querySelectorAll('#bvModel option')].some(o=>o.value==='Rebel 250'),{timeout:15000});await page.locator('#bvModel').selectOption('Rebel 250');const years=await page.locator('#bvYear option').evaluateAll(options=>options.map(o=>o.value).filter(Boolean));if(years.length)await page.locator('#bvYear').selectOption(years.includes('2021')?'2021':years[0]);await page.locator('#bvKm').fill('12000');await page.locator('#bikeValueForm button[type="submit"]').click();await page.waitForTimeout(250);expect(await page.locator('#bvSelectedBike').textContent()).toContain('Rebel 250');expectValidMoney(await page.locator('#bvCurrentValue').textContent(),'Rebel 250 current')});

test('AFB Zubatto and focused sell mix are live',async({page})=>{for(const route of ['/car-value','/sell-car','/trade-in-vs-buyback']){await gotoStable(page,route,1500);await page.waitForFunction(()=>[...document.querySelectorAll('a[href]')].some(a=>a.href.includes('track.affiliate-b.com/visit.php?a=Z209o-31470S')),{timeout:15000});expect(await page.locator('a[href*="track.affiliate-b.com/visit.php?a=Z209o-31470S"]').count(),`${route}: AFB 1470`).toBeGreaterThan(0)}for(const route of ['/sell-car','/trade-in-vs-buyback']){await gotoStable(page,route,1500);await page.waitForFunction(()=>String(document.documentElement.dataset.affiliateMix||'').startsWith('focused-v'),{timeout:15000});expect(await page.locator('[data-affiliate-provider="ユーカーパック"],.affiliate-ucarpac-v75').count(),`${route}: UcarPAC`).toBeGreaterThan(0);expect(await page.locator('.afb-zubatto-banner').count(),`${route}: duplicate AFB`).toBeLessThanOrEqual(1)}});

test('v117 final affiliate policy dedupes and assigns stable CTA experiment variants',async({page})=>{for(const route of ['/car-value','/sell-car','/trade-in-vs-buyback']){await gotoStable(page,route,1300);await page.waitForFunction(()=>document.documentElement.dataset.affiliateFinal==='v117'&&document.documentElement.dataset.affiliateExperiment==='copy-v117',{timeout:15000});const zubatto=page.locator('[data-affiliate-final="v117"][data-program="zubatto"]');expect(await zubatto.count(),`${route}: final Zubatto container`).toBeLessThanOrEqual(1);const links=page.locator('a[data-program="zubatto"][data-affiliate-variant]');expect(await links.count(),`${route}: Zubatto experiment link`).toBeGreaterThan(0);const variant=await links.first().getAttribute('data-affiliate-variant');expect(['A','B']).toContain(variant);if(route!=='/car-value'){const ucar=page.locator('[data-affiliate-final="v117"][data-program="ucarpac"]');expect(await ucar.count(),`${route}: UcarPAC final container`).toBeLessThanOrEqual(1);expect(await page.locator('[data-program="carseven"],[data-affiliate-placement*="carseven"]').count(),`${route}: legacy CarSeven`).toBe(0)}}});

test('result monetization stays hidden before calculation',async({page})=>{for(const route of ['/','/bike','/compare','/bike-compare']){await gotoStable(page,route,900);await page.waitForFunction(()=>window.__resultMonetizationV115===true,{timeout:12000});const section=page.locator('#resultMoneyV115');await expect(section,`${route}: result monetization section`).toBeAttached();await expect(section,`${route}: hidden before result`).toBeHidden()}});

test('goods query bootstrap carries vehicle query',async({page})=>{await gotoStable(page,'/car-goods?q=ホンダ%20N-BOX',2400);await page.waitForSelector('#liveGoodsQuery',{timeout:15000});await expect(page.locator('#liveGoodsQuery')).toHaveValue('ホンダ N-BOX');await gotoStable(page,'/bike-goods?q=ホンダ%20Rebel%20250',2400);await page.waitForSelector('#liveGoodsQuery',{timeout:15000});await expect(page.locator('#liveGoodsQuery')).toHaveValue('ホンダ Rebel 250')});

test('Rakuten goods client uses reusable requests and lazy product images',async({request})=>{const r=await request.get(`${base}/goods-live.js?v=7`);expect(r.status()).toBe(200);const js=await r.text();expect(js).toContain("fetch(u,{cache:'default'})");expect(js).toContain("index<2?'eager':'lazy'");expect(js).toContain('fetchpriority=');expect(js).not.toContain("searchParams.set('_'");expect(js).not.toContain("cache:'no-store'")});
