function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function auth(request,env){const x=request.headers.get('authorization')||'';return Boolean(env.ADMIN_TOKEN&&x===`Bearer ${env.ADMIN_TOKEN}`)}
function rows(x){return x?.results||[]}
const SITE_KEYS=['factory','sugutsucool','okazu','car-bike','clipmade'];
async function schema(db){await db.batch([
  db.prepare(`CREATE TABLE IF NOT EXISTS gsc_performance (id INTEGER PRIMARY KEY AUTOINCREMENT,site_key TEXT NOT NULL,snapshot_date TEXT NOT NULL,dimension TEXT NOT NULL,key TEXT NOT NULL,clicks REAL NOT NULL DEFAULT 0,impressions REAL NOT NULL DEFAULT 0,ctr REAL NOT NULL DEFAULT 0,position REAL NOT NULL DEFAULT 0,imported_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(site_key,snapshot_date,dimension,key))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS gsc_index_status (id INTEGER PRIMARY KEY AUTOINCREMENT,site_key TEXT NOT NULL,snapshot_date TEXT NOT NULL,url TEXT NOT NULL,status TEXT,reason TEXT,last_crawled TEXT,imported_at TEXT NOT NULL DEFAULT (datetime('now')),UNIQUE(site_key,snapshot_date,url))`),
  db.prepare(`CREATE TABLE IF NOT EXISTS gsc_imports (id INTEGER PRIMARY KEY AUTOINCREMENT,site_key TEXT NOT NULL,snapshot_date TEXT NOT NULL,import_type TEXT NOT NULL,file_name TEXT,row_count INTEGER NOT NULL DEFAULT 0,imported_at TEXT NOT NULL DEFAULT (datetime('now')))`),
  db.prepare(`CREATE INDEX IF NOT EXISTS idx_gsc_perf_site_date ON gsc_performance(site_key,snapshot_date)`),
  db.prepare(`CREATE INDEX IF NOT EXISTS idx_gsc_perf_dim ON gsc_performance(site_key,dimension)`),
  db.prepare(`CREATE INDEX IF NOT EXISTS idx_gsc_index_site_date ON gsc_index_status(site_key,snapshot_date)`)
])}
function parseCsv(text){const out=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c==='"'&&text[i+1]==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));out.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell.replace(/\r$/,''));out.push(row)}return out.filter(r=>r.some(x=>String(x).trim()!==''))}
function norm(v){return String(v||'').replace(/^\uFEFF/,'').trim().toLowerCase()}
function num(v){const s=String(v??'').replace(/[,%\s]/g,'');const n=Number(s);return Number.isFinite(n)?n:0}
function findHeader(headers,names){const set=names.map(norm);for(let i=0;i<headers.length;i++)if(set.includes(norm(headers[i])))return i;return-1}
function pathOf(value){const s=String(value||'').trim();if(!s)return'/';try{return s.startsWith('http')?(new URL(s).pathname||'/'):(s.startsWith('/')?s:`/${s}`)}catch{return s.startsWith('/')?s:`/${s}`}}
async function runBatches(db,statements,size=50){for(let i=0;i<statements.length;i+=size)await db.batch(statements.slice(i,i+size))}
async function tableExists(db,name){const r=await db.prepare(`SELECT 1 ok FROM sqlite_master WHERE type='table' AND name=? LIMIT 1`).bind(name).first();return Boolean(r?.ok)}
async function activityMap(db,site){const map=new Map();let available=false;try{if(site==='factory'&&await tableExists(db,'analytics_events')){const rs=rows(await db.prepare(`SELECT page_path,COUNT(*) pv FROM analytics_events WHERE event_name='page_view' AND occurred_at>=datetime('now','-30 days') GROUP BY page_path`).all());for(const r of rs)map.set(String(r.page_path||'/'),num(r.pv));available=rs.length>0}else if(site!=='factory'&&await tableExists(db,'central_events')){const rs=rows(await db.prepare(`SELECT page_path,COUNT(*) pv FROM central_events WHERE site_key=? AND event_name='page_view' AND occurred_at>=datetime('now','-30 days') GROUP BY page_path`).bind(site).all());for(const r of rs)map.set(String(r.page_path||'/'),num(r.pv));available=rs.length>0}}catch{}return{available,map}}
async function buildSiteData(db,site){const q=async(sql,b=[])=>{let s=db.prepare(sql);if(b.length)s=s.bind(...b);return rows(await s.all())},q1=async(sql,b=[])=>{let s=db.prepare(sql);if(b.length)s=s.bind(...b);return await s.first()||{}};
  const latestQuery=(await q1(`SELECT MAX(snapshot_date) snapshot_date FROM gsc_performance WHERE site_key=? AND dimension='query'`,[site])).snapshot_date||'';
  const latestPage=(await q1(`SELECT MAX(snapshot_date) snapshot_date FROM gsc_performance WHERE site_key=? AND dimension='page'`,[site])).snapshot_date||'';
  const summaryDate=latestPage||latestQuery,summaryDimension=latestPage?'page':'query';
  const previousPage=latestPage?(await q1(`SELECT MAX(snapshot_date) snapshot_date FROM gsc_performance WHERE site_key=? AND dimension='page' AND snapshot_date<?`,[site,latestPage])).snapshot_date||'':'';
  const indexLatest=(await q1(`SELECT MAX(snapshot_date) snapshot_date FROM gsc_index_status WHERE site_key=?`,[site])).snapshot_date||'';
  const imports=await q(`SELECT site_key,snapshot_date,import_type,file_name,row_count,imported_at FROM gsc_imports WHERE site_key=? ORDER BY imported_at DESC LIMIT 20`,[site]);
  if(!summaryDate)return{ok:true,configured:false,site_key:site,message:'Search Console CSV未取込',imports,opportunities:[],growing:[],declining:[],queries:[],pages:[],index_status:[],index_issues:[]};
  const summary=await q1(`SELECT SUM(clicks) clicks,SUM(impressions) impressions,CASE WHEN SUM(impressions)>0 THEN SUM(clicks)*100.0/SUM(impressions) ELSE 0 END ctr,CASE WHEN SUM(impressions)>0 THEN SUM(position*impressions)/SUM(impressions) ELSE AVG(position) END position FROM gsc_performance WHERE site_key=? AND snapshot_date=? AND dimension=?`,[site,summaryDate,summaryDimension]);
  const queries=latestQuery?await q(`SELECT key query,clicks,impressions,ctr,position FROM gsc_performance WHERE site_key=? AND snapshot_date=? AND dimension='query' ORDER BY impressions DESC LIMIT 100`,[site,latestQuery]):[];
  const pages=latestPage?await q(`SELECT key page,clicks,impressions,ctr,position FROM gsc_performance WHERE site_key=? AND snapshot_date=? AND dimension='page' ORDER BY impressions DESC LIMIT 500`,[site,latestPage]):[];
  let changes=[];if(latestPage&&previousPage)changes=await q(`SELECT c.key page,c.clicks,c.impressions,c.ctr,c.position,COALESCE(p.clicks,0) prev_clicks,COALESCE(p.impressions,0) prev_impressions,COALESCE(p.position,0) prev_position,(c.clicks-COALESCE(p.clicks,0)) click_delta,(c.impressions-COALESCE(p.impressions,0)) impression_delta,(COALESCE(p.position,0)-c.position) position_gain FROM gsc_performance c LEFT JOIN gsc_performance p ON p.site_key=c.site_key AND p.dimension='page' AND p.key=c.key AND p.snapshot_date=? WHERE c.site_key=? AND c.snapshot_date=? AND c.dimension='page' ORDER BY ABS(c.impressions-COALESCE(p.impressions,0)) DESC LIMIT 500`,[previousPage,site,latestPage]);
  const changeMap=new Map(changes.map(x=>[String(x.page),x]));
  const activity=await activityMap(db,site);
  const enrichedPages=pages.map(x=>{const ch=changeMap.get(String(x.page))||{},p=pathOf(x.page),pv30=activity.available?num(activity.map.get(p)):null;return{...x,path:p,pv_30d:pv30,click_delta:num(ch.click_delta),impression_delta:num(ch.impression_delta),position_gain:num(ch.position_gain)}});
  const opportunities=enrichedPages.map(x=>{let score=0,reason='';const imp=num(x.impressions),clicks=num(x.clicks),ctr=num(x.ctr),position=num(x.position);if(activity.available&&imp>=10&&num(x.pv_30d)===0){score=imp*8;reason='検索表示あり・サイト内PV0（30日）'}else if(imp>=20&&clicks===0){score=imp*7;reason='検索表示あり・クリック0'}else if(position>=8&&position<=20&&imp>=10){score=imp*Math.max(2,21-position);reason='順位8〜20位・SEO伸びしろ'}else if(imp>=20&&ctr<1){score=imp*4;reason='検索CTR低'}else if(num(x.impression_delta)<0&&Math.abs(num(x.impression_delta))>=10){score=Math.abs(num(x.impression_delta))*3;reason='検索表示が前回より減少'}return{...x,score,reason}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score||num(b.impressions)-num(a.impressions)).slice(0,50);
  const growing=changes.filter(x=>num(x.impression_delta)>0||num(x.click_delta)>0).sort((a,b)=>num(b.impression_delta)-num(a.impression_delta)||num(b.click_delta)-num(a.click_delta)).slice(0,30),declining=changes.filter(x=>num(x.impression_delta)<0||num(x.click_delta)<0).sort((a,b)=>num(a.impression_delta)-num(b.impression_delta)||num(a.click_delta)-num(b.click_delta)).slice(0,30);
  const indexRows=indexLatest?await q(`SELECT COALESCE(NULLIF(status,''),'未分類') status,COUNT(*) count FROM gsc_index_status WHERE site_key=? AND snapshot_date=? GROUP BY COALESCE(NULLIF(status,''),'未分類') ORDER BY count DESC`,[site,indexLatest]):[];
  const indexIssues=indexLatest?await q(`SELECT url,status,reason,last_crawled FROM gsc_index_status WHERE site_key=? AND snapshot_date=? AND lower(COALESCE(status,'')) NOT LIKE '%登録済%' AND lower(COALESCE(status,'')) NOT LIKE '%indexed%' ORDER BY url LIMIT 100`,[site,indexLatest]):[];
  return{ok:true,configured:true,site_key:site,snapshot_date:summaryDate,query_snapshot_date:latestQuery,page_snapshot_date:latestPage,previous_snapshot_date:previousPage,index_snapshot_date:indexLatest,summary,queries,pages:enrichedPages.slice(0,100),growing,declining,opportunities,index_status:indexRows,index_issues:indexIssues,imports,analytics_30d_available:activity.available};
}
export async function onRequestPost({request,env}){
  if(!auth(request,env))return json({ok:false,error:'unauthorized'},401);if(!env.ANALYTICS_DB)return json({ok:false,error:'ANALYTICS_DB missing'},503);
  let body={};try{body=await request.json()}catch{return json({ok:false,error:'invalid_json'},400)}
  const site=String(body.site_key||'').trim(),date=String(body.snapshot_date||'').trim(),type=String(body.import_type||'').trim(),file=String(body.file_name||'').slice(0,240),csv=String(body.csv||'');
  if(!SITE_KEYS.includes(site))return json({ok:false,error:'invalid_site_key'},400);if(!/^\d{4}-\d{2}-\d{2}$/.test(date))return json({ok:false,error:'invalid_snapshot_date'},400);if(!['query','page','index'].includes(type))return json({ok:false,error:'invalid_import_type'},400);if(!csv||csv.length>4_000_000)return json({ok:false,error:'invalid_or_too_large_csv'},400);
  const table=parseCsv(csv);if(table.length<2)return json({ok:false,error:'csv_has_no_rows'},400);const headers=table[0],data=table.slice(1),db=env.ANALYTICS_DB;await schema(db);const statements=[];
  if(type==='query'||type==='page'){
    const keyNames=type==='query'?['上位のクエリ','top queries','query','クエリ']:['上位のページ','top pages','page','ページ'];let ki=findHeader(headers,keyNames);if(ki<0)ki=0;
    const ci=findHeader(headers,['クリック数','clicks']),ii=findHeader(headers,['表示回数','impressions']),ti=findHeader(headers,['ctr']),pi=findHeader(headers,['掲載順位','position']);if(ci<0||ii<0||pi<0)return json({ok:false,error:'missing_performance_columns',headers},400);
    for(const r of data){const key=String(r[ki]||'').trim();if(!key)continue;const clicks=num(r[ci]),impressions=num(r[ii]),ctr=ti>=0?num(r[ti]):(impressions?clicks/impressions*100:0),position=num(r[pi]);statements.push(db.prepare(`INSERT INTO gsc_performance(site_key,snapshot_date,dimension,key,clicks,impressions,ctr,position,imported_at) VALUES(?,?,?,?,?,?,?,?,datetime('now')) ON CONFLICT(site_key,snapshot_date,dimension,key) DO UPDATE SET clicks=excluded.clicks,impressions=excluded.impressions,ctr=excluded.ctr,position=excluded.position,imported_at=datetime('now')`).bind(site,date,type,key,clicks,impressions,ctr,position))}
  }else{
    let ui=findHeader(headers,['url','ページ','page']);if(ui<0)ui=0;const si=findHeader(headers,['ステータス','status']),ri=findHeader(headers,['理由','reason']),li=findHeader(headers,['最終クロール','last crawled','last crawl']);
    for(const r of data){const url=String(r[ui]||'').trim();if(!url)continue;statements.push(db.prepare(`INSERT INTO gsc_index_status(site_key,snapshot_date,url,status,reason,last_crawled,imported_at) VALUES(?,?,?,?,?,?,datetime('now')) ON CONFLICT(site_key,snapshot_date,url) DO UPDATE SET status=excluded.status,reason=excluded.reason,last_crawled=excluded.last_crawled,imported_at=datetime('now')`).bind(site,date,url,si>=0?String(r[si]||''):'',ri>=0?String(r[ri]||''):'',li>=0?String(r[li]||''):''))}
  }
  await runBatches(db,statements);await db.prepare(`INSERT INTO gsc_imports(site_key,snapshot_date,import_type,file_name,row_count) VALUES(?,?,?,?,?)`).bind(site,date,type,file,statements.length).run();return json({ok:true,site_key:site,snapshot_date:date,import_type:type,row_count:statements.length});
}
export async function onRequestGet({request,env}){
  if(!auth(request,env))return json({ok:false,error:'unauthorized'},401);if(!env.ANALYTICS_DB)return json({ok:false,error:'ANALYTICS_DB missing'},503);
  const u=new URL(request.url),site=String(u.searchParams.get('site')||'car-bike').trim(),db=env.ANALYTICS_DB;await schema(db);
  if(site==='all'){const sites=[];for(const key of SITE_KEYS)sites.push(await buildSiteData(db,key));const topOpportunities=sites.flatMap(s=>(s.opportunities||[]).map(x=>({...x,site_key:s.site_key}))).sort((a,b)=>num(b.score)-num(a.score)).slice(0,50);return json({ok:true,portfolio:true,generated_at:new Date().toISOString(),sites:sites.map(s=>({site_key:s.site_key,configured:s.configured,snapshot_date:s.snapshot_date||'',summary:s.summary||{},opportunity_count:(s.opportunities||[]).length,analytics_30d_available:Boolean(s.analytics_30d_available),imports:(s.imports||[]).slice(0,3)})),top_opportunities:topOpportunities})}
  if(!SITE_KEYS.includes(site))return json({ok:false,error:'invalid_site_key'},400);return json(await buildSiteData(db,site));
}
